on:
  pull_request:
    paths:
      - "benches/sqlite.rs"
      - "src/*"
      - ".github/workflows/bench.yaml"
name: Benchmark
jobs:
  prepare-sqlite:
    runs-on: ubuntu-latest
    name: Prepare SQLite Database
    steps:
        
      - uses: actions/checkout@v4
      - run: sqlite3 /tmp/test.db "create table foo (a int, b text)"
  benchmark:
    name: Core Benchmarks
    needs: prepare-sqlite
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ github.base_ref }}
