on:
  pull_request:
    paths:
      - "benches/sqlite.rs"
      - "src/*"
      - ".github/workflows/bench.yaml"
name: Benchmark
jobs:
  benchmark:
    name: Core Benchmarks
    
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v4
      - run: sqlite3 /tmp/test.db "create table foo (a int, b text)"
      - uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ github.base_ref }}
