on:
  pull_request:
    paths:
      - "benches/*"
      - "src/*"
      - ".github/workflows/bench.yaml"
name: Benchmark
jobs:
  benchmark:
    name: Core Benchmarks

    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost/postgres
    steps:
      - run: cargo install sqlx-cli
      - run: git clone https://github.com/apalis-dev/apalis-postgres.git 
      - run: sqlx migrate run --source ./apalis-postgres/migrations --database-url $DATABASE_URL
      - uses: actions/checkout@v4 # v4
      - run: sqlite3 /tmp/test.db "create table foo (a int, b text)"

      - run: git clone https://github.com/apalis-dev/apalis-sqlite.git
      - run: sqlx migrate run --source ./apalis-sqlite/migrations --database-url sqlite:/tmp/test.db

      - uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ github.base_ref }}
