on:
  pull_request:
    paths:
      - "benches/sqlite.rs"
      - "src/*"
      - ".github/workflows/sqlite.yaml"
name: Benchmark
jobs:
  prepare-sqlite:
    runs-on: ubuntu-latest
    name: SQLite v3.47.2 sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup SQLite v3.47.2
        uses: actions/setup-sqlite@v1
        with:
          sqlite-version: 3.47.2
          sqlite-year: 2024
      - run: sqlite3 test.db "create table foo (a int, b text)"
  benchmark:
    name: Core Benchmarks
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ github.base_ref }}
